require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'LogRocketOnlineStore' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'LogRocketOnlineStoreTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |bc|
            bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
  end
end



target 'LogRocketOnlineStore-tvOS' do
  # Pods for LogRocketOnlineStore-tvOS

  target 'LogRocketOnlineStore-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
