require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'logrocketMobileStore' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'logrocketMobileStoreTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  post_install do |installer|
    installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
end

target 'logrocketMobileStore-tvOS' do
  # Pods for logrocketMobileStore-tvOS

  target 'logrocketMobileStore-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
